import express from "express";
import { pathToFileURL } from "node:url";
import { env, corsOrigin } from "./config/env.js";
import connectDB from "./config/db.js";
import healthRoutes from "./routes/healthRoutes.js";
import authRoutes from "./routes/authRoutes.js";
import accountRoutes from "./routes/accountRoutes.js";
import adminUserRoutes from "./routes/adminUserRoutes.js";
import alertRoutes from "./routes/alertRoutes.js";
import analyticsRoutes from "./routes/analyticsRoutes.js";
import dashboardRoutes from "./routes/dashboardRoutes.js";
import trackedChannelRoutes from "./routes/trackedChannelRoutes.js";
import suggestionRoutes from "./routes/suggestionRoutes.js";
import videoRoutes from "./routes/videoRoutes.js";
import videoAnalyticsRoutes from "./routes/videoAnalyticsRoutes.js";
import videoAnalysisRoutes from "./routes/videoAnalysisRoutes.js";
import channelAnalyticsRoutes from "./routes/channelAnalyticsRoutes.js";
import youtubeAudienceRoutes from "./routes/youtubeAudienceRoutes.js";
import ytChannelAnalysisRoutes from "./routes/ytChannelAnalysisRoutes.js";
import { accountRoutes as multiplatformAccountRoutes, competitorRoutes, postRoutes } from "./routes/multiplatformAnalyticsRoutes.js";
import { notFound, errorHandler } from "./middleware/errors.js";

const app = express();
app.disable("x-powered-by");
app.use((req, res, next) => { const origin = req.get("origin"), allowed = corsOrigin(); if (allowed === true || (Array.isArray(allowed) && allowed.includes(origin))) res.set("Access-Control-Allow-Origin", allowed === true ? "*" : origin); res.set("Access-Control-Allow-Credentials", "true"); res.set("Access-Control-Allow-Headers", "Content-Type, Authorization"); res.set("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE, OPTIONS"); if (req.method === "OPTIONS") return res.sendStatus(204); next(); });
app.use(express.json({ limit: "25mb" }));
app.use(express.urlencoded({ extended: true, limit: "25mb" }));
app.use("/api", healthRoutes);
app.use("/api/auth", authRoutes);
app.use("/api/accounts", accountRoutes);
app.use("/api/admin/users", adminUserRoutes);
app.use("/api/alerts", alertRoutes);
app.use("/api/analytics", analyticsRoutes);
app.use("/api/me", dashboardRoutes);
app.use("/api/tracked-channels", trackedChannelRoutes);
app.use("/api/suggestions", suggestionRoutes);
app.use("/api/videos", videoRoutes);
app.use("/api/videos", videoAnalyticsRoutes);
app.use("/api/video-analysis", videoAnalysisRoutes);
app.use("/api/channels", channelAnalyticsRoutes);
app.use("/api/accounts", multiplatformAccountRoutes);
app.use("/api/competitors", competitorRoutes);
app.use("/api/posts", postRoutes);
app.use("/api/youtube-audience", youtubeAudienceRoutes);
app.use("/api/yt-channel-analysis", ytChannelAnalysisRoutes);
app.use(notFound);
app.use(errorHandler);

export { app };
export async function startServer() { await connectDB(); return app.listen(env.port, "0.0.0.0", () => console.log(`Server is running on http://localhost:${env.port}`)); }
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) startServer().catch((error) => { console.error(error); process.exitCode = 1; });
