import { ConnectedAccount, Video, VideoMetric, User } from "../models/index.js";
import { getChannelInfo, getChannelVideos } from "../services/youtube.js";
import { metaOAuthUrl, tiktokOAuthUrl, exchangeMock, validMetaAppId } from "../services/oauth.js";
import { sendCsv } from "../utils/http.js";
import { now } from "../models/_base.js";

export async function getAccounts(req, res) { const filter = req.user.role === "admin" ? {} : { user_id: req.user.id }; const accounts = await ConnectedAccount.find(filter); const result = await Promise.all(accounts.map(async (a) => a.toDict(await Video.countDocuments({ connected_account_id: a.id })))); return res.json({ accounts: result }); }
export async function connectYoutube(req, res) { const data = req.body || {}, raw = String(data.channel_id || data.handle || data.url || data.channel_input || "").trim(); if (!raw) return res.status(400).json({ errors: ["channel_id, handle (@name), or channel URL is required."] }); const info = await getChannelInfo(raw); if (!info?.channel_id) return res.status(404).json({ error: "YouTube channel not found. Please check the channel ID, handle (@name), or URL." }); if (await ConnectedAccount.findOne({ user_id: req.user.id, platform: "youtube", platform_account_id: info.channel_id })) return res.status(400).json({ error: "This YouTube channel is already connected." }); const account = await ConnectedAccount.create({ user_id: req.user.id, platform: "youtube", platform_account_id: info.channel_id, display_name: info.display_name || info.channel_id, created_at: now() }); return res.status(201).json({ message: "YouTube channel connected.", account: account.toDict(0) }); }
export function instagramOAuth(req, res) { const url = metaOAuthUrl("instagram", req.user.id); return res.json({ oauth_url: url, is_mock: url.includes("mock") || !validMetaAppId() }); }
export function facebookOAuth(req, res) { const url = metaOAuthUrl("facebook", req.user.id); return res.json({ oauth_url: url, is_mock: url.includes("mock") || !validMetaAppId() }); }
export function tiktokOAuth(req, res) { const url = tiktokOAuthUrl(req.user.id); return res.json({ oauth_url: url, is_mock: url.includes("mock") }); }
export async function oauthCallback(req, res) { const data = req.method === "GET" ? req.query : req.body || {}, code = String(data.code || "").trim(), rawState = String(data.state || "").trim(), platform = req.method === "GET" ? rawState.split(":")[0] : String(data.platform || "").trim(); let user = req.user; const stateUser = rawState.split(":")[1]; if (!user && stateUser) user = await User.findOne({ id: Number(stateUser) }); if (!user) user = await User.findOne({ is_active: true }); if (!user) return res.status(401).json({ error: "Unauthorized user for OAuth callback." }); if (!code || !["instagram", "facebook", "tiktok"].includes(platform)) return res.status(400).json({ errors: ["code and valid platform are required."] }); const token = exchangeMock(platform), query = { user_id: user.id, platform, platform_account_id: token.platform_account_id }, account = await ConnectedAccount.findOne(query); if (account) { account.access_token = token.access_token; account.display_name = token.display_name || account.display_name; account.token_expires_at = new Date(Date.now() + token.expires_in * 1000); await account.save(); } else { await ConnectedAccount.create({ ...query, ...token, token_expires_at: new Date(Date.now() + token.expires_in * 1000), created_at: now() }); } if (req.method === "GET") return res.redirect("http://localhost:3000/accounts?connected=success"); return res.status(201).json({ message: `${platform[0].toUpperCase()}${platform.slice(1)} account connected successfully.`, account: (await ConnectedAccount.findOne(query)).toDict(0) }); }
export async function deleteAccount(req, res) { const account = await ConnectedAccount.findOne({ id: Number(req.params.account_id) }); if (!account) return res.status(404).json({ error: "Account not found." }); if (req.user.role !== "admin" && account.user_id !== req.user.id) return res.status(403).json({ error: "Forbidden." }); await Video.deleteMany({ connected_account_id: account.id }); await ConnectedAccount.deleteOne({ id: account.id }); return res.json({ message: "Account disconnected successfully." }); }
export async function syncAccount(req, res) { const account = await ConnectedAccount.findOne({ id: Number(req.params.account_id) }); if (!account) return res.status(404).json({ error: "Account not found." }); if (req.user.role !== "admin" && account.user_id !== req.user.id) return res.status(403).json({ error: "Forbidden." }); const rawVideos = account.platform === "youtube" ? await getChannelVideos(account.platform_account_id, 50) : []; let created = 0; for (const raw of rawVideos) { let video = await Video.findOne({ platform: account.platform, external_id: raw.external_id }); if (!video) { video = await Video.create({ connected_account_id: account.id, platform: account.platform, external_id: raw.external_id, title: raw.title || "", description: raw.description || "", tags: raw.tags || [], thumbnail_url: raw.thumbnail_url || "", duration_seconds: raw.duration_seconds, published_at: raw.published_at, fetched_at: now() }); created += 1; } const views = raw.views || 0, likes = raw.likes || 0, comments = raw.comments || 0, shares = raw.shares || 0; await VideoMetric.create({ video_id: video.id, views, likes, comments, shares, engagement_rate: Number(((likes + comments + shares) / Math.max(views, 1) * 100).toFixed(4)), recorded_at: now() }); } account.last_synced_at = now(); await account.save(); return res.json({ message: "Account synchronized successfully.", videos_fetched: rawVideos.length, new_videos: created, account: account.toDict(await Video.countDocuments({ connected_account_id: account.id })) }); }
export async function exportAccounts(req, res) { const accounts = await ConnectedAccount.find(req.user.role === "admin" ? {} : { user_id: req.user.id }); sendCsv(res, `accounts-${new Date().toISOString().slice(0, 10)}.csv`, ["platform", "display_name", "platform_account_id", "created_at"], accounts.map((a) => [a.platform, a.display_name, a.platform_account_id, a.created_at?.toISOString() || ""])); }
