import { User } from "../models/index.js";
import { checkPassword, hashPassword, signAccessToken, signPasswordResetToken, verifyPasswordResetToken } from "../utils/auth.js";
import { env } from "../config/env.js";

const EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const registerErrors = (data) => { const errors = [], email = String(data.email || "").trim(), password = data.password || "", name = String(data.full_name || "").trim(); if (!email) errors.push("Email is required."); else if (!EMAIL.test(email)) errors.push("Invalid email format."); if (!password) errors.push("Password is required."); else if (password.length < 6) errors.push("Password must be at least 6 characters."); else if (password.length > 128) errors.push("Password must not exceed 128 characters."); if (!name) errors.push("Full name is required."); else if (name.length < 2) errors.push("Full name must be at least 2 characters."); return errors; };

export async function register(req, res) { const data = req.body || {}, errors = registerErrors(data); if (errors.length) return res.status(400).json({ errors }); const email = String(data.email).trim().toLowerCase(); if (await User.findOne({ email })) return res.status(400).json({ errors: ["Email is already registered."] }); try { const user = await User.create({ email, full_name: String(data.full_name).trim(), role: "member", is_active: true, password: await hashPassword(data.password) }); return res.status(201).json({ message: "Registration successful.", access_token: signAccessToken(user), user: user.toDict() }); } catch (error) { return res.status(500).json({ error: `Registration failed: ${error.message}` }); } }
export async function login(req, res) { const email = String(req.body?.email || "").trim().toLowerCase(), password = req.body?.password || ""; if (!email || !password) return res.status(400).json({ errors: ["Email and password are required."] }); const user = await User.findOne({ email }); if (!user || !(await checkPassword(password, user.password))) return res.status(401).json({ error: "Invalid email or password." }); if (!user.is_active) return res.status(403).json({ error: "Account is deactivated. Please contact support." }); return res.status(200).json({ access_token: signAccessToken(user), user: user.toDict() }); }
export async function forgotPassword(req, res) { const email = String(req.body?.email || "").trim().toLowerCase(); if (!EMAIL.test(email)) return res.status(400).json({ errors: ["Enter a valid email address."] }); const response = { message: "If an account exists for that email, password reset instructions will be sent shortly." }; const user = await User.findOne({ email, is_active: true }); if (user && env.debug && !process.env.MAIL_SERVER) response.reset_url = `${env.frontendUrl.replace(/\/$/, "")}/auth/reset-password?token=${encodeURIComponent(signPasswordResetToken(user))}`; return res.status(200).json(response); }
export async function resetPassword(req, res) { const token = String(req.body?.token || "").trim(), password = req.body?.password || "", errors = []; if (!token) errors.push("Password reset token is required."); if (!password) errors.push("Password is required."); else if (password.length < 6) errors.push("Password must be at least 6 characters."); else if (password.length > 128) errors.push("Password must not exceed 128 characters."); if (errors.length) return res.status(400).json({ errors }); try { const payload = verifyPasswordResetToken(token); if (payload.purpose !== "password-reset" || !payload.password_fingerprint) throw new Error("invalid"); const user = await User.findOne({ id: Number(payload.user_id), email: payload.email, is_active: true }); if (!user) throw new Error("invalid"); const crypto = await import("node:crypto"), fingerprint = crypto.createHash("sha256").update(user.password).digest("hex"); if (fingerprint !== payload.password_fingerprint) throw new Error("invalid"); user.password = await hashPassword(password); await user.save(); return res.status(200).json({ message: "Password reset successfully." }); } catch (error) { return res.status(400).json({ error: error.name === "TokenExpiredError" ? "This password reset link has expired. Request a new one." : "This password reset link is invalid or has already been used." }); } }
export function logout(_req, res) { return res.status(200).json({ message: "Logged out successfully." }); }
export function profile(req, res) { return res.status(200).json({ user: req.user.toDict() }); }
export async function updateProfile(req, res) { const user = req.user, data = req.body || {}, errors = []; if ("full_name" in data) { const name = String(data.full_name).trim(); if (!name) errors.push("Full name cannot be empty."); else if (name.length < 2) errors.push("Full name must be at least 2 characters."); else user.full_name = name; } if ("email" in data) { const email = String(data.email).trim().toLowerCase(); if (!EMAIL.test(email)) errors.push("Invalid email format."); else if (await User.findOne({ email, id: { $ne: user.id } })) errors.push("Email already in use by another account."); else user.email = email; } if (data.password) { if (data.password.length < 6) errors.push("Password must be at least 6 characters."); else user.password = await hashPassword(data.password); } if (errors.length) return res.status(400).json({ errors }); try { await user.save(); return res.status(200).json({ message: "Profile updated successfully.", user: user.toDict() }); } catch (error) { return res.status(500).json({ error: `Update failed: ${error.message}` }); } }
