import { TrackedChannel, ConnectedAccount, Video, ChannelHistory } from "../models/index.js";
import { getChannelInfo, getChannelVideos } from "../services/youtube.js";
import { channelAnalytics, growthMetrics, revenue, predictSubscribers, predictViews } from "../services/analytics.js";
async function resolveChannel(value) { if (/^\d+$/.test(String(value))) { const tracked = await TrackedChannel.findOne({ id: Number(value) }); if (tracked) return tracked; const account = await ConnectedAccount.findOne({ id: Number(value), platform: "youtube" }); if (account) return account; } const tracked = await TrackedChannel.findOne({ channel_id: String(value) }); if (tracked) return tracked; const info = await getChannelInfo(value); return info?.channel_id ? info : null; }
export async function detail(req, res) { const found = await resolveChannel(req.params.channel_id); if (!found) return res.status(404).json({ error: "Channel not found." }); let channel, videos = [], history = []; if (found instanceof TrackedChannel || found.constructor.modelName === "TrackedChannel") { channel = found.toDict(await Video.countDocuments({ tracked_channel_id: found.id })); videos = await Video.find({ tracked_channel_id: found.id }); history = await ChannelHistory.find({ channel_id: found.channel_id }).sort({ recorded_at: 1 }); } else if (found instanceof ConnectedAccount || found.constructor.modelName === "ConnectedAccount") { channel = { id: found.id, channel_id: found.platform_account_id, channel_name: found.display_name, platform: found.platform, subscriber_count: 0, total_views: 0, video_count: await Video.countDocuments({ connected_account_id: found.id }) }; videos = await Video.find({ connected_account_id: found.id }); } else { channel = { id: null, channel_id: found.channel_id, channel_name: found.display_name, subscriber_count: found.subscriber_count || 0, total_views: found.total_views || 0, video_count: found.video_count || 0, profile_image: found.thumbnail, banner_url: found.banner_url, data_source: found.data_source }; videos = await getChannelVideos(found.channel_id, 50); } const dicts = await Promise.all(videos.map((v) => v.toDict ? v.toDict() : v)); return res.json({ channel, analytics: channelAnalytics(channel, dicts) }); }
export async function history(req, res) { const found = await resolveChannel(req.params.channel_id), id = found?.channel_id || found?.platform_account_id || String(req.params.channel_id), records = await ChannelHistory.find({ channel_id: id }).sort({ recorded_at: 1 }); return res.json({ channel_id: id, count: records.length, history: records.map((r) => r.toDict()) }); }
export async function growth(req, res) { const found = await resolveChannel(req.params.channel_id); if (!found) return res.status(404).json({ error: "Channel not found." }); const channel = found.toDict ? found.toDict() : found, records = found.channel_id ? await ChannelHistory.find({ channel_id: found.channel_id }).sort({ recorded_at: 1 }) : []; return res.json({ channel_id: channel.channel_id, growth: growthMetrics(records, channel) }); }
export async function channelRevenue(req, res) { const found = await resolveChannel(req.params.channel_id); if (!found) return res.status(404).json({ error: "Channel not found." }); const channel = found.toDict ? found.toDict() : found, records = found.channel_id ? await ChannelHistory.find({ channel_id: found.channel_id }).sort({ recorded_at: 1 }) : [], growth = growthMetrics(records, channel), low = Number(req.query.low_cpm || 2), high = Number(req.query.high_cpm || 8); return res.json({ channel_id: channel.channel_id, revenue_estimate: revenue(growth.monthly_growth.views || growth.average_daily_views * 30, channel.total_views, low, high) }); }
export async function predictions(req, res) { const found = await resolveChannel(req.params.channel_id); if (!found) return res.status(404).json({ error: "Channel not found." }); const channel = found.toDict ? found.toDict() : found, records = found.channel_id ? await ChannelHistory.find({ channel_id: found.channel_id }).sort({ recorded_at: 1 }) : []; return res.json({ channel_id: channel.channel_id, subscriber_predictions: predictSubscribers(records, channel.subscriber_count || channel.subscribers || 0), view_predictions: predictViews(records, channel.total_views || 0) }); }
export async function topVideos(req, res) { const found = await resolveChannel(req.params.channel_id); if (!found) return res.status(404).json({ error: "Channel not found." }); const list = found.constructor?.modelName === "TrackedChannel" ? await Video.find({ tracked_channel_id: found.id }) : found.constructor?.modelName === "ConnectedAccount" ? await Video.find({ connected_account_id: found.id }) : await getChannelVideos(found.channel_id, 50), videos = await Promise.all(list.map((v) => v.toDict ? v.toDict() : v)), sort = String(req.query.sort_by || "views").toLowerCase(); videos.sort((a, b) => (b[sort] || 0) - (a[sort] || 0)); return res.json({ channel_id: found.channel_id || found.platform_account_id, count: videos.length, top_videos: videos.slice(0, 20) }); }
