import { ConnectedAccount, TrackedChannel, AccountHistory, PostHistory, Video } from "../models/index.js";
import { growthMetrics, predictSubscribers, predictViews, aiScores, revenue, seo } from "../services/analytics.js";
async function account(id) { return ConnectedAccount.findOne({ id: Number(id) }); }
export async function accountGrowth(req, res) { const item = await account(req.params.account_id); if (!item) return res.status(404).json({ error: "Account not found." }); const history = await AccountHistory.find({ platform_account_id: item.platform_account_id, platform: item.platform }).sort({ recorded_at: 1 }); return res.json({ account: item.toDict(await Video.countDocuments({ connected_account_id: item.id })), growth: growthMetrics(history, item.toDict()) }); }
export async function accountPredictions(req, res) { const item = await account(req.params.account_id); if (!item) return res.status(404).json({ error: "Account not found." }); const history = await AccountHistory.find({ platform_account_id: item.platform_account_id, platform: item.platform }).sort({ recorded_at: 1 }), dict = item.toDict(); return res.json({ account: dict, follower_predictions: predictSubscribers(history, dict.followers || 0), view_predictions: predictViews(history, dict.total_views || 0) }); }
export async function accountCompetitors(req, res) { const item = await account(req.params.account_id); if (!item) return res.status(404).json({ error: "Account not found." }); const competitors = await TrackedChannel.find({ platform: item.platform }).limit(5); return res.json({ account: item.toDict(), competitors_count: competitors.length, competitor_comparisons: competitors.map((c) => ({ competitor: c.toDict(), status: "comparison_pending" })) }); }
export async function compare(req, res) { const userAccount = req.body?.user_account_id ? await account(req.body.user_account_id) : null, competitor = req.body?.competitor_channel_id ? await TrackedChannel.findOne({ channel_id: String(req.body.competitor_channel_id) }) : null, user = userAccount?.toDict() || { display_name: "My Channel", subscribers: 5000, platform: "youtube" }, other = competitor?.toDict() || { channel_name: "Competitor Channel", subscribers: 12000, platform: "youtube" }, uScore = aiScores(user), cScore = aiScores(other), us = user.subscribers || 0, cs = other.subscriber_count || other.subscribers || 0; return res.json({ comparison: { user: { name: user.display_name || "User Account", platform: user.platform, followers: us, total_views: user.total_views || 0, post_count: 0, overall_score: uScore.overall_score, engagement_score: uScore.scores.engagement_score, revenue_estimate: revenue(user.total_views || 0) }, competitor: { name: other.channel_name || "Competitor Account", platform: other.platform, followers: cs, total_views: other.total_views || 0, post_count: 0, overall_score: cScore.overall_score, engagement_score: cScore.scores.engagement_score, revenue_estimate: revenue(other.total_views || 0) } }, gaps: { follower_gap: us - cs, views_gap: (user.total_views || 0) - (other.total_views || 0), score_gap: Number((uScore.overall_score - cScore.overall_score).toFixed(1)), leader: us >= cs ? "User" : "Competitor" }, highlights: [`Follower lead: ${us >= cs ? `User is ahead by ${Math.abs(us - cs)}` : `Competitor leads by ${Math.abs(us - cs)} followers`}.`] }); }
export async function postAnalytics(req, res) { const post = await Video.findOne({ id: Number(req.params.post_id) }); if (!post) return res.status(404).json({ error: "Post/Video not found." }); const dict = await post.toDict(), score = aiScores({ platform: post.platform }, [dict]); return res.json({ post: dict, analytics: { views: dict.views, likes: dict.likes, comments: dict.comments, shares: dict.shares, engagement_rate: dict.engagement_rate, quality_score: score.scores.content_quality_score } }); }
export async function postSeo(req, res) { const post = await Video.findOne({ id: Number(req.params.post_id) }); if (!post) return res.status(404).json({ error: "Post/Video not found." }); return res.json({ post_id: post.id, seo: seo(await post.toDict()) }); }
export async function postPrediction(req, res) { const post = await Video.findOne({ id: Number(req.params.post_id) }); if (!post) return res.status(404).json({ error: "Post/Video not found." }); const history = await PostHistory.find({ external_id: post.external_id }).sort({ recorded_at: 1 }), dict = await post.toDict(); return res.json({ post_id: post.id, prediction: predictViews(history, dict.views) }); }
