import { Suggestion, SuggestionSource, ConnectedAccount, TrackedChannel, Video } from "../models/index.js";
import { SUGGESTION_TYPES } from "../models/Suggestion.js";
import { generateSuggestion, AIProviderError } from "../services/ai.js";
import { sendCsv, sendTextPdf } from "../utils/http.js";
export async function generate(req, res) { const data = req.body || {}, errors = []; if (!SUGGESTION_TYPES.includes(data.type)) errors.push(`type must be one of: ${SUGGESTION_TYPES.join(", ")}`); if (!data.connected_account_id && !data.tracked_channel_id) errors.push("Either connected_account_id or tracked_channel_id is required."); if (data.connected_account_id && data.tracked_channel_id) errors.push("Provide only one of connected_account_id or tracked_channel_id."); if (errors.length) return res.status(400).json({ errors }); let target, filter; if (data.connected_account_id) { target = await ConnectedAccount.findOne({ id: Number(data.connected_account_id) }); if (!target) return res.status(404).json({ error: "Connected account not found." }); if (req.user.role !== "admin" && target.user_id !== req.user.id) return res.status(403).json({ error: "Forbidden." }); filter = { connected_account_id: target.id }; } else { target = await TrackedChannel.findOne({ id: Number(data.tracked_channel_id) }); if (!target) return res.status(404).json({ error: "Tracked channel not found." }); filter = { tracked_channel_id: target.id }; } const videos = await Video.find(filter).sort({ fetched_at: -1 }).limit(50), videoDicts = await Promise.all(videos.map((v) => v.toDict())); let output; try { output = generateSuggestion(data.type, videoDicts, target.display_name || target.channel_name, data.provider); } catch (error) { if (error instanceof AIProviderError) return res.status(400).json({ error: error.message }); throw error; } const suggestion = await Suggestion.create({ user_id: req.user.id, connected_account_id: data.connected_account_id ? Number(data.connected_account_id) : null, tracked_channel_id: data.tracked_channel_id ? Number(data.tracked_channel_id) : null, type: data.type, input_context: `Account: ${target.display_name || target.channel_name} | Type: ${data.type} | Videos analyzed: ${videos.length}`, output }); await Promise.all(videos.slice(0, 10).map((v) => SuggestionSource.create({ suggestion_id: suggestion.id, video_id: v.id }))); return res.status(201).json({ message: "Suggestion generated.", suggestion: suggestion.toDict(Math.min(videos.length, 10)) }); }
export async function list(req, res) { const suggestions = await Suggestion.find(req.user.role === "admin" ? {} : { user_id: req.user.id }).sort({ created_at: -1 }); return res.json({ suggestions: suggestions.map((s) => s.toDict(0)) }); }
export async function get(req, res) { const suggestion = await Suggestion.findOne({ id: Number(req.params.suggestion_id) }); if (!suggestion) return res.status(404).json({ error: "Suggestion not found." }); if (req.user.role !== "admin" && suggestion.user_id !== req.user.id) return res.status(403).json({ error: "Forbidden." }); const links = await SuggestionSource.find({ suggestion_id: suggestion.id }), videos = await Promise.all(links.map(async (link) => { const video = await Video.findOne({ id: link.video_id }); return video ? { ...(await video.toDict()), source_link_id: link.id } : null; })); return res.json({ suggestion: { ...suggestion.toDict(links.length), source_videos: videos.filter(Boolean) } }); }
export async function remove(req, res) { const suggestion = await Suggestion.findOne({ id: Number(req.params.suggestion_id) }); if (!suggestion) return res.status(404).json({ error: "Suggestion not found." }); if (req.user.role !== "admin" && suggestion.user_id !== req.user.id) return res.status(403).json({ error: "Forbidden." }); await SuggestionSource.deleteMany({ suggestion_id: suggestion.id }); await Suggestion.deleteOne({ id: suggestion.id }); return res.json({ message: "Suggestion deleted." }); }
export async function exportSuggestions(req, res) { const suggestions = await Suggestion.find(req.user.role === "admin" ? {} : { user_id: req.user.id }); const rows = suggestions.map((s) => [s.type, s.connected_account_id || s.tracked_channel_id || "—", typeof s.output === "object" ? Object.values(s.output || {})[0] || "" : s.output || "", s.created_at?.toISOString() || ""]); if (req.query.format === "pdf") return sendTextPdf(res, `suggestions-${new Date().toISOString().slice(0, 10)}.pdf`, "Social Pulse — Suggestions", [{ body: rows.map((r) => r.join(" | ")).join("\n") }]); return sendCsv(res, `suggestions-${new Date().toISOString().slice(0, 10)}.csv`, ["type", "target", "output_summary", "created_at"], rows); }
export async function exportOne(req, res) { const result = await getSuggestionObject(req); if (result.error) return res.status(result.error.status).json(result.error.body); return sendTextPdf(res, `suggestion-${result.suggestion.id}-${new Date().toISOString().slice(0, 10)}.pdf`, `Social Pulse — ${result.suggestion.type} Suggestion Report`, [{ heading: "Generated Output", body: JSON.stringify(result.suggestion.output, null, 2) }]); }
export async function sources(req, res) { const suggestion = await Suggestion.findOne({ id: Number(req.params.suggestion_id) }); if (!suggestion) return res.status(404).json({ error: "Suggestion not found." }); if (req.user.role !== "admin" && suggestion.user_id !== req.user.id) return res.status(403).json({ error: "Forbidden." }); const links = await SuggestionSource.find({ suggestion_id: suggestion.id }); const sourceVideos = (await Promise.all(links.map(async (link) => { const video = await Video.findOne({ id: link.video_id }); return video ? { ...(await video.toDict()), source_id: link.id, source_created_at: link.created_at?.toISOString() } : null; }))).filter(Boolean); return res.json({ suggestion_id: suggestion.id, source_count: sourceVideos.length, source_videos: sourceVideos }); }
export async function videoSuggestions(req, res) { const video = await Video.findOne({ id: Number(req.params.video_id) }); if (!video) return res.status(404).json({ error: "Video not found." }); const links = await SuggestionSource.find({ video_id: video.id }), suggestions = (await Promise.all(links.map(async (link) => { const suggestion = await Suggestion.findOne({ id: link.suggestion_id }); return suggestion && (req.user.role === "admin" || suggestion.user_id === req.user.id) ? { ...suggestion.toDict(), source_link_id: link.id } : null; }))).filter(Boolean); return res.json({ video_id: video.id, suggestions_count: suggestions.length, suggestions }); }
async function getSuggestionObject(req) { const suggestion = await Suggestion.findOne({ id: Number(req.params.suggestion_id) }); if (!suggestion) return { error: { status: 404, body: { error: "Suggestion not found." } } }; if (req.user.role !== "admin" && suggestion.user_id !== req.user.id) return { error: { status: 403, body: { error: "Forbidden." } } }; return { suggestion }; }
