import { ConnectedAccount, Video, VideoMetric, ThumbnailAnalysis } from "../models/index.js";
import { sendCsv, sendTextPdf } from "../utils/http.js";
export async function getVideos(req, res) { const filter = {}; if (req.user.role !== "admin") { const ids = (await ConnectedAccount.find({ user_id: req.user.id })).map((a) => a.id); filter.$or = [{ connected_account_id: { $in: ids } }, { tracked_channel_id: { $ne: null } }]; } if (req.query.account_id) filter.connected_account_id = Number(req.query.account_id); if (req.query.tracked_channel_id) filter.tracked_channel_id = Number(req.query.tracked_channel_id); if (req.query.platform) filter.platform = req.query.platform; const videos = await Video.find(filter).sort({ published_at: -1 }); return res.json({ videos: await Promise.all(videos.map((v) => v.toDict())) }); }
export async function getVideo(req, res) { const video = await Video.findOne({ id: Number(req.params.video_id) }); if (!video) return res.status(404).json({ error: "Video not found." }); if (!(await ownsVideo(req.user, video))) return res.status(403).json({ error: "Forbidden." }); return res.json({ video: await video.toDict() }); }
export async function getVideoMetrics(req, res) { const video = await Video.findOne({ id: Number(req.params.video_id) }); if (!video) return res.status(404).json({ error: "Video not found." }); if (!(await ownsVideo(req.user, video))) return res.status(403).json({ error: "Forbidden." }); const metrics = await VideoMetric.find({ video_id: video.id }).sort({ recorded_at: 1 }); return res.json({ metrics: metrics.map((m) => m.toDict()) }); }
export async function exportVideos(req, res) { const filter = req.user.role === "admin" ? {} : { connected_account_id: { $in: (await ConnectedAccount.find({ user_id: req.user.id })).map((a) => a.id) } }; const videos = await Video.find(filter); const rows = []; for (const video of videos) { const metric = await VideoMetric.findOne({ video_id: video.id }).sort({ recorded_at: -1 }); rows.push([video.platform, video.title || "", metric?.views || 0, metric?.likes || 0, metric?.comments || 0, video.published_at?.toISOString() || ""]); } const filename = `videos-${new Date().toISOString().slice(0, 10)}`; if (req.query.format === "pdf") return sendTextPdf(res, `${filename}.pdf`, "Social Pulse — Video Performance Report", [{ heading: "Videos", body: rows.map((row) => row.join(" | ")).join("\n") }]); return sendCsv(res, `${filename}.csv`, ["platform", "title", "views", "likes", "comments", "published_at"], rows); }
export async function thumbnailCreate(req, res) { const video = await Video.findOne({ id: Number(req.params.video_id) }); if (!video) return res.status(404).json({ error: "Video not found." }); if (!(await ownsVideo(req.user, video))) return res.status(403).json({ error: "Forbidden." }); if (await ThumbnailAnalysis.findOne({ video_id: video.id })) return res.status(400).json({ error: "Thumbnail analysis already exists for this video." }); const analysis = await ThumbnailAnalysis.create({ video_id: video.id, dominant_colors: ["#FF6B35", "#004E98", "#FFFFFF"], has_text: true, face_count: 1, composition_notes: "Thumbnail features high-contrast colors with clear subject. Text overlay is readable.", score: 0.82 }); return res.status(201).json({ message: "Thumbnail analysis created.", thumbnail_analysis: analysis.toDict() }); }
export async function thumbnailGet(req, res) { const video = await Video.findOne({ id: Number(req.params.video_id) }); if (!video) return res.status(404).json({ error: "Video not found." }); if (!(await ownsVideo(req.user, video))) return res.status(403).json({ error: "Forbidden." }); const analysis = await ThumbnailAnalysis.findOne({ video_id: video.id }); return analysis ? res.json({ thumbnail_analysis: analysis.toDict() }) : res.status(404).json({ error: "Thumbnail analysis not found." }); }
async function ownsVideo(user, video) { if (user.role === "admin" || !video.connected_account_id) return true; return Boolean(await ConnectedAccount.findOne({ id: video.connected_account_id, user_id: user.id })); }
