import { AudienceAnalysisRun, AudienceComment, AudienceCommentAnalysis, Video } from "../models/index.js";
import { sendCsv, sendTextPdf } from "../utils/http.js";
import { extractVideoId } from "../services/transcript.js";
const ACTIVE = ["PENDING", "FETCHING", "PREPROCESSING", "CLASSIFYING", "CLUSTERING", "ANALYZING", "AGGREGATING", "SUMMARIZING"];
function usage(count, all) { return { requested_count: count, all_available: all, estimated_comments: all ? "all available" : count, estimated_batches: all ? null : Math.ceil(count / 150) }; }
function countRequested(value) { if (value === "all" || value === null || value === undefined) return [null, true]; const count = Number(value); if (!Number.isInteger(count) || count < 1) throw new Error("requested_count must be a positive integer or 'all'."); return [Math.min(count, 10000), false]; }
async function owned(req, id) { const run = await AudienceAnalysisRun.findOne({ id: Number(id) }); if (!run) return { error: { status: 404, body: { error: "Audience analysis run not found." } } }; if (req.user.role !== "admin" && run.user_id !== req.user.id) return { error: { status: 403, body: { error: "Forbidden. Access denied." } } }; return { run }; }
export async function estimate(req, res) { const id = extractVideoId(req.body?.video_url || ""); if (!id) return res.status(400).json({ error: "A valid YouTube video URL is required." }); try { const [count, all] = countRequested(req.body?.requested_count ?? 500); return res.json({ video_id: id, usage: usage(count, all) }); } catch (error) { return res.status(400).json({ error: error.message }); } }
export async function start(req, res) { const videoUrl = String(req.body?.video_url || "").trim(), provider = String(req.body?.provider || "auto").toLowerCase(); if (!["auto", "gemini", "claude"].includes(provider)) return res.status(400).json({ error: "provider must be auto, gemini, or claude." }); const videoId = extractVideoId(videoUrl); if (!videoId) return res.status(400).json({ error: "A valid YouTube video URL is required." }); let count, all; try { [count, all] = countRequested(req.body?.requested_count ?? 500); } catch (error) { return res.status(400).json({ error: error.message }); } const duplicate = await AudienceAnalysisRun.findOne({ user_id: req.user.id, external_video_id: videoId, status: { $in: ACTIVE } }).sort({ created_at: -1 }); if (duplicate) return res.status(202).json({ message: "An analysis for this video is already running.", run: await duplicate.toDict(false), usage: usage(count, all) }); let video = await Video.findOne({ platform: "youtube", external_id: videoId }); if (!video) video = await Video.create({ platform: "youtube", external_id: videoId, title: "Video metadata pending" }); const run = await AudienceAnalysisRun.create({ user_id: req.user.id, video_fk_id: video.id, external_video_id: videoId, video_url: videoUrl, status: "PENDING", requested_count: count, requested_all: all, current_stage: "PENDING", configuration_json: { provider, usage: usage(count, all) } }); return res.status(202).json({ message: "Audience analysis queued.", run: await run.toDict(false), usage: usage(count, all) }); }
export async function getRun(req, res) { const result = await owned(req, req.params.run_id); if (result.error) return res.status(result.error.status).json(result.error.body); return res.json({ run: await result.run.toDict(true) }); }
export async function deleteRun(req, res) { const result = await owned(req, req.params.run_id); if (result.error) return res.status(result.error.status).json(result.error.body); await AudienceCommentAnalysis.deleteMany({ run_id: result.run.id }); await AudienceAnalysisRun.deleteOne({ id: result.run.id }); return res.json({ message: "Audience analysis run deleted." }); }
export async function history(req, res) { const runs = await AudienceAnalysisRun.find({ user_id: req.user.id }).sort({ created_at: -1 }).limit(50); return res.json({ count: runs.length, history: await Promise.all(runs.map((run) => run.toDict(false))) }); }
export async function comments(req, res) { const result = await owned(req, req.params.run_id); if (result.error) return res.status(result.error.status).json(result.error.body); const page = Number(req.query.page || 1), perPage = Math.min(100, Number(req.query.per_page || 25)); if (!Number.isInteger(page) || !Number.isInteger(perPage) || page < 1 || perPage < 1) return res.status(400).json({ error: "page and per_page must be valid integers." }); const analyses = await AudienceCommentAnalysis.find({ run_id: result.run.id }), byId = new Map(analyses.map((a) => [a.comment_id, a])), filter = { video_fk_id: result.run.video_fk_id }; if (req.query.min_likes) filter.like_count = { $gte: Number(req.query.min_likes) }; if (req.query.min_replies) filter.reply_count = { $gte: Number(req.query.min_replies) }; if (req.query.q) filter.$or = [{ original_text: { $regex: String(req.query.q).slice(0, 200), $options: "i" } }, { author_name: { $regex: String(req.query.q).slice(0, 200), $options: "i" } }]; const all = await AudienceComment.find(filter).sort({ published_at: -1 }), filtered = all.filter((comment) => { const analysis = byId.get(comment.id); if (!analysis) return false; for (const field of ["sentiment", "emotion", "language", "topic", "intent", "persona", "cluster"]) if (req.query[field] && analysis[field] !== req.query[field]) return false; if (["true", "false"].includes(req.query.spam) && analysis.is_spam !== (req.query.spam === "true")) return false; if (["true", "false"].includes(req.query.toxicity) && analysis.is_toxic !== (req.query.toxicity === "true")) return false; return true; }), rows = filtered.slice((page - 1) * perPage, page * perPage); return res.json({ page, per_page: perPage, total: filtered.length, comments: rows.map((comment) => comment.toDict(byId.get(comment.id))) }); }
export async function exportCsv(req, res) { const result = await owned(req, req.params.run_id); if (result.error) return res.status(result.error.status).json(result.error.body); const analyses = await AudienceCommentAnalysis.find({ run_id: result.run.id }), byId = new Map(analyses.map((a) => [a.comment_id, a])), comments = await AudienceComment.find({ video_fk_id: result.run.video_fk_id }).sort({ published_at: 1 }), rows = comments.filter((c) => byId.has(c.id)).map((c) => { const a = byId.get(c.id); return [c.external_comment_id, c.parent_external_comment_id, c.author_name, c.author_channel_id, c.original_text, c.published_at?.toISOString() || "", c.updated_at?.toISOString() || "", c.like_count, c.reply_count, a.language, a.sentiment, a.emotion, a.topic, a.intent, a.persona, a.cluster, a.is_spam, a.is_toxic, a.is_sarcastic, a.quality_score, a.confidence]; }); return sendCsv(res, `youtube-audience-${result.run.external_video_id}-${result.run.id}.csv`, ["comment_id", "parent_comment_id", "author", "author_channel_id", "text", "published_at", "updated_at", "likes", "replies", "language", "sentiment", "emotion", "topic", "intent", "persona", "cluster", "spam", "toxicity", "sarcasm", "quality_score", "confidence"], rows); }
export async function exportPdf(req, res) { const result = await owned(req, req.params.run_id); if (result.error) return res.status(result.error.status).json(result.error.body); return sendTextPdf(res, `youtube-audience-${result.run.external_video_id}-${result.run.id}.pdf`, "YouTube Audience Intelligence Report", [{ heading: "Executive Summary", body: result.run.report_json?.executive_summary || "Report is still processing." }, { heading: "Video Information", fields: [["Video ID", result.run.external_video_id], ["Requested", result.run.requested_all ? "All available" : result.run.requested_count], ["Analyzed", result.run.analyzed_count]] }]); }
export async function purgeComments(req, res) { const runs = await AudienceAnalysisRun.find({ user_id: req.user.id, external_video_id: req.params.video_id }); if (!runs.length) return res.status(404).json({ error: "No audience analysis found for this video." }); const ids = runs.map((r) => r.id); await AudienceCommentAnalysis.deleteMany({ run_id: { $in: ids } }); return res.json({ message: "Stored comments and classifications were purged.", video_id: req.params.video_id }); }
