export function growthMetrics(history, current = null) {
  const items = history.map((item) => item?.toDict ? item.toDict() : item);
  if (current && (!items.length || items.at(-1).date !== new Date().toISOString().slice(0, 10))) items.push({ subscribers: current.subscriber_count || current.subscribers || current.followers || 0, total_views: current.total_views || 0, total_videos: current.video_count || current.total_videos || current.total_posts || 0, date: new Date().toISOString().slice(0, 10) });
  const empty = { daily_subscriber_growth: 0, daily_view_growth: 0, daily_video_growth: 0, weekly_growth: { subscribers: 0, views: 0, videos: 0 }, monthly_growth: { subscribers: 0, views: 0, videos: 0 }, yearly_growth: { subscribers: 0, views: 0, videos: 0 }, average_daily_views: 0, average_daily_subscribers: 0, growth_velocity: 0, growth_trend: "stable", growth_percentage: 0, rolling_7d_avg_views: 0, rolling_30d_avg_views: 0, rolling_90d_avg_views: 0 };
  if (!items.length) return empty;
  if (items.length < 2) { const latest = items.at(-1); return { ...empty, average_daily_views: latest.total_views || 0, average_daily_subscribers: latest.subscribers || 0, growth_velocity: 1, rolling_7d_avg_views: latest.total_views || 0, rolling_30d_avg_views: latest.total_views || 0, rolling_90d_avg_views: latest.total_views || 0 }; }
  const latest = items.at(-1), previous = items.at(-2);
  const diff = (field) => (latest[field] || 0) - (previous[field] || 0);
  const ref = (n) => items[Math.max(0, items.length - n)];
  const viewDiffs = items.slice(1).map((item, i) => Math.max(0, (item.total_views || 0) - (items[i].total_views || 0)));
  const avg = (n) => Number((viewDiffs.slice(-n).reduce((a, b) => a + b, 0) / Math.max(1, viewDiffs.slice(-n).length)).toFixed(2));
  const avgSub = items.slice(1).reduce((sum, item, i) => sum + Math.max(0, (item.subscribers || 0) - (items[i].subscribers || 0)), 0) / Math.max(1, items.length - 1);
  const recent = items.slice(-7); const recentSub = recent.slice(1).reduce((sum, item, i) => sum + Math.max(0, (item.subscribers || 0) - (recent[i].subscribers || 0)), 0) / Math.max(1, recent.length - 1);
  const velocity = Number((recentSub / Math.max(avgSub, 0.1)).toFixed(2));
  const value = (item, field) => item[field] || 0;
  const growth = (n) => ({ subscribers: value(latest, "subscribers") - value(ref(n), "subscribers"), views: value(latest, "total_views") - value(ref(n), "total_views"), videos: value(latest, "total_videos") - value(ref(n), "total_videos") });
  return { daily_subscriber_growth: diff("subscribers"), daily_view_growth: diff("total_views"), daily_video_growth: diff("total_videos"), weekly_growth: growth(7), monthly_growth: growth(30), yearly_growth: growth(365), average_daily_views: avg(30), average_daily_subscribers: Number(avgSub.toFixed(2)), growth_velocity: velocity, growth_trend: velocity > 1.2 ? "accelerating" : velocity < 0.8 ? "decelerating" : "stable", growth_percentage: Number((((value(latest, "subscribers") - value(items[0], "subscribers")) / Math.max(value(items[0], "subscribers"), 1)) * 100).toFixed(2)), rolling_7d_avg_views: avg(7), rolling_30d_avg_views: avg(30), rolling_90d_avg_views: avg(90) };
}

export function predictSubscribers(history, current) { const rates = history.slice(1).map((item, i) => Math.max(0, (item.subscribers || 0) - (history[i].subscribers || 0))).filter((v) => v >= 0); const rate = Math.max(1, rates.length ? rates.reduce((a, b) => a + b, 0) / rates.length : current * 0.001); const confidence = rates.length > 30 ? 92.5 : rates.length > 7 ? 85 : rates.length > 1 ? 72 : 60; const prediction = (days) => ({ days, predicted_subscribers: Math.floor(current + rate * days), gained: Math.floor(rate * days) }); return { current_subscribers: current, daily_growth_rate: Number(rate.toFixed(2)), confidence_percentage: confidence, predictions: { tomorrow: prediction(1), in_7_days: prediction(7), in_30_days: prediction(30), in_90_days: prediction(90), in_1_year: prediction(365) } }; }
export function predictViews(history, current) { const diffs = history.slice(1).map((item, i) => Math.max(0, (item.total_views || 0) - (history[i].total_views || 0))); const rate = Math.max(50, diffs.length ? diffs.reduce((a, b) => a + b, 0) / diffs.length : current * 0.005); const confidence = diffs.length > 30 ? 90 : diffs.length > 7 ? 80 : 65; return { current_total_views: current, avg_daily_views: Number(rate.toFixed(2)), confidence_percentage: confidence, predictions: { daily_views: Math.floor(rate), weekly_views: Math.floor(rate * 7), monthly_views: Math.floor(rate * 30), yearly_views: Math.floor(rate * 365), expected_total_views_in_1y: current + Math.floor(rate * 365) } }; }
export function revenue(monthlyViews, lifetime = 0, low = 2, high = 8) { const monthly = Math.max(0, Number(monthlyViews) || 0), total = Math.max(monthly, Number(lifetime) || 0), range = (views, min, max) => ({ min_usd: Number((views / 1000 * min).toFixed(2)), max_usd: Number((views / 1000 * max).toFixed(2)), formatted: `$${(views / 1000 * min).toFixed(2)} - $${(views / 1000 * max).toFixed(2)}` }); return { disclaimer: "Estimates only based on CPM formula. Actual earnings depend on audience geo, ad fill rate, and niche.", config: { low_cpm_usd: low, high_cpm_usd: high }, daily: range(monthly / 30, low, high), monthly: range(monthly, low, high), yearly: range(monthly * 12, low, high), lifetime: range(total, low, high) }; }
export function viral(video) { const views = Math.max(0, video.views || 0), likes = Math.max(0, video.likes || 0), comments = Math.max(0, video.comments || 0); let hours = 24; if (video.published_at) hours = Math.max(1, (Date.now() - new Date(video.published_at).getTime()) / 3600000); const vph = views / hours, lph = likes / hours, cph = comments / hours, engagement = (likes + comments) / Math.max(views, 1) * 100, vs = Math.min(40, vph / 500 * 40), ls = Math.min(30, (lph + cph * 2) / 50 * 30), es = Math.min(20, engagement / 10 * 20), rs = Math.max(0, 10 - hours / 24 * 2), score = Math.min(100, Number((vs + ls + es + rs).toFixed(1))); return { viral_score: score, viral_level: score >= 80 ? "Mega Viral" : score >= 60 ? "High Viral" : score >= 40 ? "Moderate Viral" : "Standard", metrics: { views_per_hour: Number(vph.toFixed(2)), likes_per_hour: Number(lph.toFixed(2)), comments_per_hour: Number(cph.toFixed(2)), views_per_minute: Number((vph / 60).toFixed(2)), engagement_rate: Number(engagement.toFixed(2)), upload_age_hours: Number(hours.toFixed(1)) }, breakdown: { view_velocity_score: Number(vs.toFixed(1)), interaction_velocity_score: Number(ls.toFixed(1)), engagement_score: Number(es.toFixed(1)), recency_boost: Number(rs.toFixed(1)) } }; }
export function seo(video) { const title = (video.title || "").trim(), description = (video.description || "").trim(), tags = video.tags || [], recommendations = []; let score = 0; if (title.length >= 30 && title.length <= 70) score += 30; else if (title.length >= 15 && title.length <= 90) { score += 20; recommendations.push("Adjust title length to 30-70 characters for optimal search visibility and CTR."); } else if (title) { score += 10; recommendations.push("Title is too short or too long. Aim for 30-70 impactful characters."); } else recommendations.push("Video missing title. Add a keyword-rich title."); if (description.length >= 250) score += 25; else if (description.length >= 100) { score += 15; recommendations.push("Expand video description to over 250 characters with detailed timestamps and relevant links."); } else if (description) { score += 8; recommendations.push("Description is very brief. Add comprehensive summary, timestamps, and keywords."); } else recommendations.push("Missing video description. Write a detailed 250+ character description."); if (tags.length >= 8) score += 20; else if (tags.length >= 4) { score += 12; recommendations.push("Add more targeted tags (aim for 8-15 tags covering broad and niche terms)."); } else if (tags.length) { score += 5; recommendations.push("Very few tags found. Include relevant topic, niche, and brand hashtags/tags."); } else recommendations.push("No tags found. Add 8-15 relevant search tags."); if (video.thumbnail_url) score += 15; else recommendations.push("Missing high-resolution thumbnail image."); if (video.category) score += 10; else recommendations.push("Set an explicit video category (e.g. Science & Technology, Education)."); if (!recommendations.length) recommendations.push("Excellent SEO optimization! Keep maintaining strong keyword placement and thumbnail contrast."); return { seo_score: score, title_length: title.length, description_length: description.length, tags_count: tags.length, has_thumbnail: Boolean(video.thumbnail_url), has_category: Boolean(video.category), recommendations }; }
export function channelAnalytics(channel, videos) { const subscribers = Math.max(1, channel.subscriber_count || channel.subscribers || 0), totalViews = Math.max(0, channel.total_views || 0), count = Math.max(videos.length, channel.video_count || channel.total_videos_count || 0), avg = (field) => videos.length ? Number((videos.reduce((sum, v) => sum + (v[field] || 0), 0) / videos.length).toFixed(2)) : Number((totalViews / Math.max(count, 1)).toFixed(2)); const avgViews = avg("views"), avgLikes = avg("likes"), avgComments = avg("comments"), engagement = (avgLikes + avgComments) / Math.max(avgViews, 1) * 100, activity = Math.min(100, videos.length ? videos.length / 8 * 100 : 50), consistency = Math.min(100, videos.length ? videos.length / 8 * 100 : 50), popularity = Math.min(100, subscribers / 100000 * 100), growth = Math.min(100, avgViews / 10000 * 100), engagementScore = Math.min(100, engagement / 5 * 100), overall = Number((activity * .15 + consistency * .2 + engagementScore * .3 + popularity * .15 + growth * .2).toFixed(1)); return { channel_grade: overall >= 85 ? "A+" : overall >= 75 ? "A" : overall >= 65 ? "B+" : overall >= 50 ? "B" : "C", overall_channel_score: overall, averages: { average_views_per_video: avgViews, average_likes_per_video: avgLikes, average_comments_per_video: avgComments }, ratios: { subscriber_to_view_ratio: Number((subscribers / Math.max(totalViews, 1) * 100).toFixed(4)), views_per_subscriber: Number((totalViews / subscribers).toFixed(2)) }, upload_frequency: { videos_per_week: Number((videos.length / 4 || 1).toFixed(2)), videos_per_month: videos.length || 4 }, scores: { activity_score: Number(activity.toFixed(1)), consistency_score: Number(consistency.toFixed(1)), engagement_score: Number(engagementScore.toFixed(1)), popularity_score: Number(popularity.toFixed(1)), growth_score: Number(growth.toFixed(1)), overall_score: overall } }; }
export function aiScores(account, posts = []) { const followers = account.subscriber_count || account.subscribers || account.followers || 0, profile = Math.min(100, (account.description || account.niche ? 40 : 10) + (account.profile_image || account.banner_url ? 40 : 10) + Math.min(20, followers / 5000 * 20)), seoScore = posts.length ? Math.min(100, posts.reduce((s, p) => s + Math.min(50, (p.title || "").length / 40 * 50) + (p.tags?.length ? 50 : 0), 0) / posts.length) : 70, views = posts.reduce((s, p) => s + (p.views || 0), 0), interactions = posts.reduce((s, p) => s + (p.likes || 0) + (p.comments || 0) + (p.shares || 0), 0), engagement = posts.length ? Math.min(100, interactions / Math.max(views, 1) * 1500) : 65, consistency = Math.min(100, posts.length / 10 * 100), content = seoScore * .4 + engagement * .6, audience = Math.min(100, followers / 10000 * 50 + engagement * .5), brand = Math.min(100, profile * .3 + audience * .4 + consistency * .3), creator = engagement * .35 + content * .35 + 50 * .3, overall = Number((profile * .1 + 50 * .15 + seoScore * .15 + engagement * .25 + consistency * .15 + brand * .1 + creator * .1).toFixed(1)); return { overall_score: overall, scores: { profile_score: Number(profile.toFixed(1)), growth_score: 50, seo_score: Number(seoScore.toFixed(1)), engagement_score: Number(engagement.toFixed(1)), consistency_score: Number(consistency.toFixed(1)), content_quality_score: Number(content.toFixed(1)), audience_quality_score: Number(audience.toFixed(1)), brand_score: Number(brand.toFixed(1)), creator_score: Number(creator.toFixed(1)), overall_score: overall } }; }
